import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'

export default function Home() {
  return (
    <div className="bg-zinc-100">
      <Head>
        <title>Emelyn Barrientos</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Sora:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 py-10 min-h-screen">
        <section>
          <nav className="flex justify-between mb-6">
            <h1 className="text-xl font-semibold">Emelyn Barrientos</h1>
            <ul className="flex">
              <li>
                <BsFillMoonStarsFill className="text-2xl" />
              </li>
            </ul>
          </nav>
          <nav className="flex justify-start">
            <ul className="flex">
              <li className="font-medium mr-8">
                <a
                  href="https://github.com/emelyn-barrientos/"
                  target="_blank"
                  rel="noreferrer"
                >
                  Github
                </a>
              </li>
              <li className="font-medium mr-8">
                <a
                  href="https://www.linkedin.com/in/emelyn-barrientos/"
                  target="_blank"
                  rel="noreferrer"
                >
                  LinkedIn
                </a>
              </li>
              <li className="font-medium mr-8">CV/Resume</li>
              <li className="font-medium mr-8">
                <a
                  href="mailto: emelyn.barrientos22@gmail.com"
                  target="_blank"
                  rel="noreferrer"
                >
                  Email
                </a>
              </li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  )
}
